language: ruby

cache: bundler

services:
  - mongodb

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
    - rvm: 2.3.1
        env:
          - DATABASE_ADAPTER=pg
    - rvm: 2.3.1
        env:
          - DATABASE_ADAPTER=mongoid

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

